### ISSUE TITLE
Latest version results in concurrent read/write of map

### ISSUE THREAD

**Issue by Phasip** [tgragnato/magnetico#176]
Edit: I called it deadlock first, but first line indicates concurrent read/write of map:
`fatal error: concurrent map iteration and map write`

Not sure how to help debug, but the output is attached.
[trace.txt](https://github.com/tgragnato/magnetico/files/14646847/trace.txt)

**Comment by Phasip** [comment]
https://github.com/tgragnato/magnetico/pull/177

**Comment by tgragnato** [comment]
No problem, it's this map. https://github.com/tgragnato/magnetico/blob/c34259bfea5bbccb11d96f91b5ff1014ae8f4955/dht/mainline/indexingService.go#L27

I have been finding bugs in the routing table for a while. With more frequent accesses, the risk of collision is greater.

I would like to refactor this code, also because in its current form unit testing is really hard
