### ISSUE TITLE
addNode function occupies too much memory and does not release it

### ISSUE THREAD

**Issue by lazyoop** [tgragnato/magnetico#464]
### During use, it was found that the addNode function occupied a large amount of memory over time and was not released, eventually leading to system memory exhaustion.   

**git :** ac5125fc2cbd12753636f0d1eeaffff0d31537a5

pprof:   
![addNodeMem](https://github.com/user-attachments/assets/52915123-38d2-405a-a93e-913432860ad8)

I think the problem is caused by slicing.   
![append](https://github.com/user-attachments/assets/17169bb1-8c59-4e3e-ad0b-fbdd4027bb70)

I am not sure if it is appropriate to use the copy() function to solve this problem through online query.

**Comment by tgragnato** [comment]
Hi there,

Thank you for reaching out!

Your pprof output shows excessive RAM usage related to the functions `(*IndexingService).onSampleInfohashesResponse` and `(*routingTable).addNode`, not the data structure of the routing table itself.

**This indicates an excessive crawling rate**: the daemon is unable to efficiently utilize the discovered DHT nodes quickly enough.

It is not useful to perform crawling as fast as possible if you cannot effectively use the discovered nodes. I would like to avoid implementing code that abuses the Mainline DHT. So my recommendation is to use this flag to limit the crawling rate of the DHT: `--max-rps=<max_requests_per_second>`.

Regarding your question about using the `copy()` function, it seems unrelated to the provided code snippet. The `copy()` function in Go is used to copy elements from one slice to another. It might not be necessary in this particular scenario since the code is simply appending a node to the nodes slice.

However, I have not fully understood your suggestion. If you have a specific problem or requirement that you think the `copy()` function can help with, please provide more details so that I can assist you further.

I also accept draft PRs. 🦾

If you need any further adjustments, feel free to ask!
