### ISSUE TITLE
latest tag is not latest?

### ISSUE THREAD

**Issue by gigawatts** [tgragnato/magnetico#471]
Using the instructions in your readme to pull the "latest" tag (linux/amd64) seems to pull a non-functional image that results in a SIGSEGV when run. Conversely, pulling the "next" tag (from instructions here: https://github.com/tgragnato/magnetico/pkgs/container/magnetico) released 2 hours ago (at time of writing) pulled a different image that works

**Comment by tgragnato** [comment]
I’m still working on **adjusting the workflows** and **removing inadequate dependencies**, which is why you pulled a non-functioning container. I’m sorry about that.

I’m not sure if the approach with tags is right, so any feedback is welcome. I use the next tag for the latest successful build that has passed the tests. The latest tag is for the most recent release.
